parameters:
    influxdb.url: '%env(INFLUXDB_URL)%'
    influxdb.token: '%env(INFLUXDB_TOKEN)%'
    influxdb.org: '%env(INFLUXDB_ORG)%'
    influxdb.bucket: '%env(INFLUXDB_BUCKET)%'

services:
    App\Service\MonitoringService:
        arguments:
            $influxdbUrl: '%influxdb.url%'
            $influxdbToken: '%influxdb.token%'
            $influxdbOrg: '%influxdb.org%'
            $influxdbBucket: '%influxdb.bucket%'
            $logger: '@monolog.logger.influxdb'

    monolog.logger.influxdb:
        parent: monolog.logger
        tags: ['monolog.logger', 'monolog.influxdb'] 