# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    upload_directory: "%kernel.project_dir%/public/assets/images/learnMzansi"
    openai_api_key: "%env(OPENAI_API_KEY)%"
    app.ai_endpoint: "%env(AI_ENDPOINT)%"
    app.ai_api_key: "%env(AI_API_KEY)%"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Configure the api logger
    api_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: ["api"]
        tags:
            - { name: monolog.logger, channel: api }

    App\Service\Base\BaseLearnMzansiService:
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
            $apiLogger: "@monolog.logger.api"

    App\Controller\LearnMzansiApiController:
        arguments:
            $api: '@App\Service\LearnMzansiApi'
            $logger: "@monolog.logger.api"

    App\EventListener\CorsListener:
        tags:
            - { name: kernel.event_subscriber }

    App\Service\LearnMzansiApi:
        arguments:
            $projectDir: "%kernel.project_dir%"
            $openAiKey: "%env(OPENAI_API_KEY)%"

    App\Service\SmsPortalService:
        arguments:
            $apiKey: "%env(SMS_API_KEY)%"
            $apiSecret: "%env(SMS_API_SECRET)%"

    App\Service\WhatsAppService:
        arguments: []

    App\Service\LearnerEventService:
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
            $logger: "@monolog.logger.api"

    App\Service\QuestionTopicService:
        arguments:
            $openAiKey: "%openai_api_key%"

    App\Service\OpenAIService:
        arguments:
            $openaiApiKey: "%openai_api_key%"

    App\Service\CareerAdviceService:
        arguments:
            $openaiApiKey: "%openai_api_key%"
            $entityManager: "@doctrine.orm.entity_manager"
            $logger: "@monolog.logger.api"
            $reportService: '@App\Service\LearnerReportService'

    App\Service\ReportedMessageService:
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
            $logger: "@monolog.logger.api"

    App\Service\QuestionNumberExtractorService:
        arguments:
            $params: "@parameter_bag"
            $logger: "@logger"
            $httpClient: "@http_client"

    App\Service\ImageUploadService:
        arguments:
            $targetDirectory: "%kernel.project_dir%/public/assets/images/learnMzansi"
            $slugger: '@Symfony\Component\String\Slugger\SluggerInterface'

    App\Service\SubscriptionService:
        arguments:
            $entityManager: '@Doctrine\ORM\EntityManagerInterface'
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $revenueCatApiKey: "%env(REVENUECAT_API_KEY)%"
